//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 169
        ///150
        ///158
        ///163
        ///167
        ///151
        ///152
        ///153
        ///154
        ///159
        ///168
        ///176
        ///182
        ///183
        ///188
        ///182
        ///183
        ///184
        ///185
        ///195
        ///199
        ///198
        ///196
        ///211
        ///212
        ///202
        ///203
        ///208
        ///205
        ///204
        ///205
        ///226
        ///208
        ///191
        ///193
        ///195
        ///199
        ///200
        ///198
        ///200
        ///199
        ///214
        ///241
        ///247
        ///242
        ///238
        ///227
        ///228
        ///236
        ///238
        ///242
        ///246
        ///248
        ///236
        ///243
        ///259
        ///261
        ///262
        ///265
        ///264
        ///273
        ///277
        ///279
        ///275
        ///279
        ///295
        ///290
        ///296
        ///288
        ///285
        ///297
        ///296
        ///311
        ///321
        ///346
        ///351
        ///361
        ///391
        ///395
        ///401
        ///397
        ///410
        ///415
        ///417
        ///422
        ///400
        ///396
        ///425
        ///421
        ///426
        ///427
        ///429
        ///430
        ///462
        ///461
        ///462
        ///467
        ///475
        ///479
        ///481
        ///483
        ///487
        ///494
        ///496
        ///511
        ///510
        ///511
        ///514
        ///524
        ///530
        ///532
        ///522
        ///505
        ///516
        ///502
        ///489
        ///488
        ///501
        ///503
        ///479
        ///500
        ///503
        ///507
        ///514
        ///522
        ///532
        ///533
        ///535
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 6
        ///down 3
        ///forward 8
        ///down 5
        ///forward 9
        ///down 2
        ///up 9
        ///down 9
        ///forward 8
        ///down 3
        ///down 8
        ///forward 2
        ///down 1
        ///up 3
        ///up 6
        ///up 9
        ///down 7
        ///up 7
        ///down 1
        ///forward 7
        ///down 7
        ///up 4
        ///down 2
        ///forward 8
        ///up 3
        ///up 1
        ///down 1
        ///down 6
        ///up 2
        ///down 5
        ///forward 4
        ///down 5
        ///down 3
        ///forward 4
        ///down 3
        ///up 8
        ///forward 1
        ///up 9
        ///forward 2
        ///up 7
        ///down 2
        ///down 9
        ///down 1
        ///down 6
        ///down 8
        ///down 6
        ///down 1
        ///down 1
        ///down 9
        ///down 9
        ///down 2
        ///forward 9
        ///down 1
        ///forward 4
        ///down 2
        ///forward 6
        ///down 8
        ///forward 4
        ///forward 8
        ///forward 4
        ///forward 4
        ///up 4
        ///up 9
        ///down 6
        ///forward 2
        ///forward 5
        ///down 2
        ///forward 1
        ///d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111010011
        ///110011001100
        ///010011111000
        ///101001100011
        ///011011100110
        ///110100011011
        ///001000001010
        ///011011101000
        ///110011001000
        ///001011101010
        ///100000001000
        ///001000000111
        ///111110110101
        ///101000100110
        ///110101110001
        ///101101010111
        ///000010001001
        ///101110010100
        ///101000101011
        ///010110100011
        ///110010011001
        ///110110011111
        ///100111000001
        ///100101010011
        ///101011011001
        ///111101110010
        ///000111000001
        ///000000000111
        ///011010111101
        ///101010100011
        ///010001001011
        ///100011010100
        ///100000011110
        ///000010110100
        ///101001110100
        ///000110110000
        ///101100101000
        ///111001100111
        ///110100001110
        ///00111 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3Input {
            get {
                return ResourceManager.GetString("Day3Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,69,28,50,36,84,49,13,48,90,1,33,71,0,94,59,53,58,60,96,30,34,29,91,11,41,77,95,17,80,85,93,7,9,74,89,18,25,26,8,87,38,68,5,12,43,27,46,62,73,16,55,22,4,65,76,54,52,83,10,21,67,15,47,45,40,35,66,79,51,75,39,64,24,37,72,3,44,82,32,78,63,57,2,86,31,19,92,14,97,20,56,88,81,70,61,42,99,23,98
        ///
        ///22 59  7 10  6
        ///33 36 96 55 23
        ///13 85 18 29 28
        ///75 46 83 73 58
        ///34 40 87 56 98
        ///
        ///73 96 47 14 10
        ///28 11 79 84 20
        ///74 30  0 59 71
        ///80 93 42 22 17
        ///44  2 81 29 15
        ///
        ///73 32 37 93 39
        /// 2 87 38 99 97
        ///15 12 42 49 33
        /// 9 23 25 94 19
        ///57  4 18  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 973,543 -&gt; 601,915
        ///758,846 -&gt; 758,168
        ///511,976 -&gt; 568,976
        ///858,536 -&gt; 858,677
        ///256,238 -&gt; 265,238
        ///475,919 -&gt; 718,919
        ///973,912 -&gt; 134,73
        ///984,159 -&gt; 175,968
        ///166,641 -&gt; 15,490
        ///504,798 -&gt; 504,946
        ///717,796 -&gt; 128,207
        ///302,713 -&gt; 168,713
        ///830,964 -&gt; 830,444
        ///151,288 -&gt; 549,686
        ///530,908 -&gt; 820,908
        ///540,394 -&gt; 717,394
        ///581,614 -&gt; 581,496
        ///111,593 -&gt; 230,712
        ///938,884 -&gt; 938,917
        ///923,71 -&gt; 20,974
        ///530,677 -&gt; 530,332
        ///144,723 -&gt; 144,980
        ///700,376 -&gt; 700,917
        ///501,95 -&gt; 198,95
        ///251,900 -&gt; 435,900
        ///912,931 -&gt; 96,115
        ///962,140 -&gt; 181,921
        ///104,24 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
    }
}
